name: David Elbe
description: "Helping freelancers to build awesome web agencies"
meta_description: "The personal website of David Elbe. Entrepreneur, developer and problem-solver."
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://david.elbe.me/'
author:         'David Elbe'

gems:
  - jekyll-redirect-from
